Update veracode-pipeline-scan.yml

diff --git a/.github/workflows/veracode-pipeline-scan.yml b/.github/workflows/veracode-pipeline-scan.yml
--- a/.github/workflows/veracode-pipeline-scan.yml
+++ b/.github/workflows/veracode-pipeline-scan.yml
@@ -163,13 +163,18 @@ jobs:
           repo_name: ${{ inputs.repo }}
           commitHash: ${{ inputs.sha }}
 
-      - name: Set job status
-        if: success()
-        run: echo "status=success" >> $GITHUB_OUTPUT
-
-      - name: Set job status
-        if: failure()
-        run: echo "status=failure" >> $GITHUB_OUTPUT
+      - name: Set output for step2
+        if: always()  # Ensures this runs even if step2 fails.
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "step${{ strategy.job-index }}_status=success" >> $GITHUB_ENV
+          else
+            echo "step${{ strategy.job-index }}_status=failure" >> $GITHUB_ENV
+        env:
+          GITHUB_ENV: $GITHUB_ENV
+      - name: Export all outputs
+        run: |
+          echo "step${{ strategy.job-index }}_status=${{ env.step${{ strategy.job-index }}_status }}" >> $GITHUB_OUTPUT
 
   update-checks-status:
     runs-on: ubuntu-latest
